# Generated by Django 3.1.3 on 2020-11-29 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.PositiveIntegerField(default=0)),
                ('zip', models.PositiveIntegerField(default=0)),
                ('comments', models.TextField()),
                ('name1', models.CharField(max_length=50)),
                ('cnumber', models.PositiveIntegerField(default=0)),
                ('expm', models.CharField(max_length=50)),
                ('expy', models.PositiveIntegerField(default=0)),
                ('cvv', models.PositiveIntegerField(default=0)),
                ('arrive', models.DateTimeField()),
                ('depart', models.DateTimeField()),
                ('guest', models.PositiveIntegerField(default=0)),
                ('rooms', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
